config/routes.rb
Rails.application.routes.draw do
  get 'settings/index'
  get 'historico/index'
  resources :valordoses
  get 'static_pages/inadimplente'
  root 'welcome#index'
  get 'admin', to: 'admin#index'
  get 'dadosuser', to: 'admin#dadosuser'
  get '/manager_users', to: 'manager_users#index', as: 'manager_users_index'
  get 'inadimplente', to: 'static_pages#inadimplente'
  resources :employees
  devise_for :users
  resources :keylockers 
  get 'historico', to: 'historico#index'
  get '/atualizar_soma_dinamica', to: 'keylockers#atualizar_soma_dinamica'

  get '/dispensers', to: 'keylockers#index', as: 'dispensers'
  get '/user_dispenser', to: 'manager_users#index', as: 'user_dispenser'
  get '/dispensers/new', to: 'keylockers#new', as: 'new_dispenser'

  get '/dispensers/:id', to: 'keylockers#show', as: 'dispenser', constraints: { id: /\d+/ }
  get '/dispensers/:id/edit', to: 'keylockers#edit', as: 'edit_dispenser', constraints: { id: /\d+/ }
  post 'user_mailer/send_email', to: 'user_mailer#send_email'
  post '/enviar_mensagem_whatsapp/:id', to: 'employees#enviar_mensagem_whatsapp', as: 'enviar_mensagem_whatsapp'


  resources :settings, only: [:index, :create]

  resources :employees do
    member do
      patch 'toggle_and_save_status'
      put 'reset_pin'
      post 'employees/send_email', to: 'employees#send_email'
      post 'send_email'
      post 'send_sms'
      post 'import', to: 'employees#import'
    end
    collection do
      post 'import', to: 'employees#import'
    end
  end

  resources :keylockers do
    member do
      post 'reset_counter'
      patch 'toggle_and_save_status'
    end
  end

  patch 'manager_users/:id/toggle_finance', to: 'manager_users#toggle_finance', as: :toggle_finance
  patch 'manager_users/:id/toggle_role', to: 'manager_users#toggle_role', as: :toggle_role

  resources :manager_users do
    member do
      delete :destroy
    end
  end

  get '/history_entries', to: 'history_entries#index'

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]

  resources :history_entries, only: [:index, :show, :new, :create, :destroy]


  # config/routes.rb
  resources :user_lockers do
    member do
      post 'assign_keylocker'
      delete 'remove_keylocker/:keylocker_id', to: 'user_lockers#remove_keylocker', as: 'remove_keylocker'
    end
  end

  

  #resources :keylockers, defaults: { format: 'json' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :employees
      post 'employees/check_access', to: 'employees#check_access'
      get '/employees', to: 'employees#index'
      post '/register_card', to: 'employees#register_card'
      post '/create_user', to: 'employees#create_user'
      get '/employees/:employee_id/belongs_to_keylocker/:keylocker_id', to: 'employees#belongs_to_keylocker'
      post '/libera_dose', to: 'employees#libera_dose', via: :post
      post 'check_user', to: 'employees#check_user'
      post 'count_and_track_spaces', to: 'employees#count_and_track_spaces'
      post 'return_key', to: 'employees#return_key'
      post 'key_locker_history', to: 'employees#key_locker_history'
      get '/outro_metodo', to: 'employees#outro_metodo'
      resources :keylockers do
        member do
          post 'increment_counter'
        end
      end
      #post '/auth/sign_in', to: 'authentication#sign_in'
      devise_for :users, skip: [:registrations], controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :keylockers
    has_one_attached :profile_picture
    has_many :employee_actions

    validate :at_least_one_keylocker

  
    private

    def at_least_one_keylocker
      errors.add(:base, 'Deve haver pelo menos um dispenser atribuído') if keylockers.none?
    end
  
    
  end
  

app/models/employee_action.rb
class EmployeeAction < ApplicationRecord
    belongs_to :employee
end

app/controllers/api/v1/employees_controller.rb
I18n.locale = :pt

module Api
  module V1
    class EmployeesController < ApplicationController
      skip_before_action :verify_authenticity_token, only: [:libera_dose, :register_card, :create_user, :check_access]
      skip_before_action :authenticate_user!, only: [:libera_dose, :register_card, :create_user, :check_access]

      def libera_dose
        card_rfid = params[:cardRFID]
        employee = Employee.find_by(cardRFID: card_rfid)
      
        if employee
          log_message = "Acesso liberado para Name: #{employee.name}, Lastname: #{employee.lastname}, CompanyID: #{employee.companyID}, Phone: #{employee.phone}, Function: #{employee.function}"
          save_log(log_message, employee)
          render json: {
            name: employee.name,
            lastname: employee.lastname,
            companyID: employee.companyID,
            phone: employee.phone,
            function: employee.function
          }, status: :ok
        else
          render json: { message: "Acesso negado" }, status: :unprocessable_entity
        end
      end
      
      def check_access
        card_rfid = params[:cardRFID]
        employee = Employee.find_by(cardRFID: card_rfid)

        if employee
          render json: { message: "Acesso liberado", employee: employee }, status: :ok
        else
          render json: { message: "Acesso negado" }, status: :unprocessable_entity
        end
      end
      
      def register_card
        rfid_user = params[:cardRFID]
    
        # Verifica se o cartão já está cadastrado
        existing_employee = Employee.find_by(cardRFID: rfid_user)
    
        if existing_employee
          render json: { message: 'Este cartão já está cadastrado.', employee_id: existing_employee.id }
        else
          # Cria um novo funcionário com base no número do cartão
          new_employee = Employee.create(cardRFID: rfid_user)
    
          if new_employee.valid?
            render json: { message: 'Funcionário cadastrado com sucesso.', employee_id: new_employee.id }
          else
            render json: { message: 'Falha ao cadastrar funcionário.', errors: new_employee.errors.full_messages }
          end
        end
      end

      def create_user
        if params[:cardRFID]
          card_rfid = params[:cardRFID]
          history_entry = HistoryEntry.find_by(saveCards: card_rfid)
          save_card(card_rfid)
          HistoryEntryDestroyJob.set(wait: 5.minutes).perform_later
          render json: { message: "Cartão RFID #{card_rfid} salvo com sucesso." }, status: :ok
        else
          render json: { error: "Parâmetro cardRFID ausente." }, status: :unprocessable_entity
        end
      end
      
      private

      def save_log(message, employee)
        Log.create(message: message, employee_info: {
          name: employee.name,
          lastname: employee.lastname,
          companyID: employee.companyID,
          phone: employee.phone,
          function: employee.function
        })
      end

      def save_card(card_rfid)
        HistoryEntry.create(saveCards: card_rfid)
      end

      def allow_cors
        # Configuração para permitir solicitações de origens diferentes (CORS)
        response.headers['Access-Control-Allow-Origin'] = '*'
        response.headers['Access-Control-Allow-Methods'] = 'POST, PUT, PATCH, GET, OPTIONS'
        response.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
      end

    end
  end
end

app/controllers/employees_controller.rb
require 'cgi'
require 'rest-client'

class EmployeesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:toggle_and_save_status, :reset_pin, :send_sms_with_new_pin, :destroy]
  skip_before_action :authenticate_user!, only: [:toggle_and_save_status, :reset_pin, :send_sms_with_new_pin, :destroy]
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /employees or /employees.json
  def index
    if current_user.admin?
      #@employees = Employee.all
      @employees = Employee.includes(:user).all.paginate(page: params[:page], per_page: 9)
      @users = User.all.includes(:keylockers, employee: :keylocker).paginate(page: params[:page], per_page: 9)
    else
      @employees = Employee.where(user_id: current_user.id).paginate(page: params[:page], per_page: 9)
    end
  end

  # GET /employees/1 or /employees/1.json
  def show
    @employee = Employee.find(params[:id])
    @employee_actions = @employee.employee_actions
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.user = current_user  
    @employee.keylockers = current_user.keylockers
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Funcionário foi criado com sucesso." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Funcionário foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Funcionário foi deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  def enviar_mensagem_whatsapp
    url = 'https://v5.chatpro.com.br/chatpro-6m8favcrd9/api/v1/send_message'
    headers = {
      'Authorization': '51b3f07ad623b39e4dc6ce9af96551a8',
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    }
    @employee = Employee.find(params[:id])
  
    phone = @employee.phone
    nome = @employee.name
    sobrenome = @employee.lastname
    numeroapart = @employee.numberHouse
  
    puts "Enviando Whatsapp para #{nome} #{sobrenome} (Apartamento #{numeroapart})..."
    mensagem = "Olá #{nome} #{sobrenome}, morador do #{numeroapart} sua encomenda chegou e encontra na portaria"

    payload = {
      number: phone,
      message: mensagem
    }

    #redirect_to employee_path(@employee), notice: 'Whatsapp enviado com sucesso!'

    @employee.employee_actions.create(
    action_type: "Enviar Whatsapp",
    action_description: "Whatsapp enviado para o morador em #{Time.zone.now.strftime("%d/%m/%Y - %H:%M")}"
    )

    begin
      response = RestClient.post(url, payload.to_json, headers)
      render json: { success: true, response: response.body }
    rescue RestClient::ExceptionWithResponse => e
      render json: { success: false, error: e.response.body }, status: e.response.code
    rescue RestClient::Exception => e
      render json: { success: false, error: e.message }, status: :internal_server_error
    end
  end

  def send_sms
    @employee = Employee.find(params[:id])
  
    phone = @employee.phone
    nome = @employee.name
    sobrenome = @employee.lastname
    numeroapart = @employee.numberHouse
  
    puts "Enviando SMS para #{nome} #{sobrenome} (Apartamento #{numeroapart})..."
  
    message = "Ola #{nome}, morador do apto. #{numeroapart}. Sua encomenda chegou na portaria do seu predio!"
    send_sms_to_employee(phone, message)
    redirect_to employee_path(@employee), notice: 'SMS enviado com sucesso!'

    @employee.employee_actions.create(
    action_type: "Enviar SMS",
    action_description: "SMS enviado para o morador em #{Time.zone.now.strftime("%d/%m/%Y - %H:%M")}"
    )
  end

  def import
    begin
      file = params[:file]
      spreadsheet = Roo::Spreadsheet.open(file.path)
      header = spreadsheet.row(1)
      
      ActiveRecord::Base.transaction do
        (2..spreadsheet.last_row).each do |i|
          row = Hash[[header, spreadsheet.row(i)].transpose]
          employee = Employee.new
          employee.attributes = row.to_hash.slice("name", "lastname", "numberHouse", "phone", "email")
          employee.user = current_user
          employee.keylockers = current_user.keylockers
          employee.save!
        end
      end
      
      redirect_to employees_path, notice: "Planilha importada com sucesso!"
    rescue StandardError => e
      redirect_to employees_path, alert: "Erro ao importar a planilha: #{e.message}"
    end
  end
  

  def send_email
    @employee = Employee.find(params[:id])

    # Configurando as configurações de e-mail
    ActionMailer::Base.smtp_settings = {
      address:              'smtp.gmail.com',
      port:                 465,
      user_name:            'smartmailbuilding@gmail.com',
      password:             'ebzzwrvykwihempj',
      authentication:       'plain',
      enable_starttls_auto: true,
      tls:                  true
    }

    # Enviar o e-mail
    UserMailer.send_email(@employee).deliver_now

    redirect_to employee_path(@employee), notice: 'E-mail enviado com sucesso!'
    @employee.employee_actions.create(
      action_type: "Enviar Email",
      action_description: "Email enviado para o morador em #{Time.zone.now.strftime("%d/%m/%Y - %H:%M")}"
      )  
  end
 
  def toggle_and_save_status
    @employee = Employee.find(params[:id])
    @employee.update(status: (@employee.status == 'bloqueado' ? 'desbloqueado' : 'bloqueado'))
    respond_to do |format|
      format.json { render json: { status: @employee.status } }
    end
  end

  
  private

    def send_sms_to_employee(phone, message)
      # Busca a última chave da API salva no banco de dados
      api_key = Setting.last&.key
      puts "API KEY: #{api_key}"
      puts "PHONE: #{phone}"
      puts "MESSAGE: #{message}"

      #api_key = '05LleS23oQMPDXClXuLl' # Substitua pela sua chave de API

      
      # Verifica se há uma chave da API disponível
      if api_key.present?
        # Adicionando os parâmetros diretamente na URL com a chave da API encontrada
        url = "https://sistema81.smsbarato.com.br/send?chave=#{CGI.escape(api_key)}&dest=#{CGI.escape(phone)}&text=#{CGI.escape(message)}"
        
        puts "Fazendo solicitação POST para: #{url}"
        begin
          # Fazendo a solicitação GET
          response = RestClient.post(url, {})
          puts "Resposta do servidor: #{response.body}"
          puts "Código de status: #{response.code}"
        rescue RestClient::ExceptionWithResponse => e
          puts "Erro na solicitação: #{e.response.body}"
          puts "Código de status: #{e.response.code}"
        end
      else
        puts "Nenhuma chave da API encontrada"
        # Retorna um erro apropriado ou lida com a situação de outra maneira
    raise "Nenhuma chave da API encontrada"
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :lastname, :numberHouse, :phone, :email, :profile_picture)
    end
end

app/helpers/api/v1/employees_helper.rb
module Api::V1::EmployeesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <% if employee.profile_picture.attached? %>
    <%= image_tag employee.profile_picture %>
    <% else %>
      <p>Nenhuma imagem disponível</p>
    <% end %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= employee.name %> <%= employee.lastname %>
  </p>

  <p>
    <strong>Empresa:</strong>
    <%= employee.companyID %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= employee.phone %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= employee.function %>
  </p>

  <p>
    <strong>Código Pin:</strong>
    <%= employee.PIN %>
  </p>

  <p>
    <strong>Senha Locker:</strong>
    <%= employee.pswdSmartlocker %>
  </p>

  <p>
    <strong>ID Card:</strong>
    <%= employee.cardRFID %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= employee.status %>
  </p>

  <% employee.workdays.each do |workday| %>

  <p>
    <strong>Dias de trabalho:</strong>
    <% days_of_week = JSON.parse(workday.dayofweek) rescue [] %>
    <ul>
      <% days_of_week.each do |day| %>
        <li><%= day %></li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Hora de inicio</strong>
    <%= workday.start.strftime("%H:%M") %>
  </p>


  <p>
    <strong>Hora de termino:</strong>
    <%= workday.end.strftime("%H:%M") %>
  </p>

  <p>
    <strong>Trabalha no Feriado</strong>
    <%= workday.holiday ? 'Sim' : 'Não' %>
  </p>

  <% end %>
</div>

app/views/employees/edit.html.erb
<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-users"></i> Meus Moradores</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<%= form_with(url: import_employees_path, method: :post, multipart: true) do |form| %>
  <%= form.file_field :file, class: "form-control", accept: ".xls,.xlsx" %>
  <%= form.submit "Importar Planilha", class: "btn btn-primary mt-3" %>
<% end %>

<p style="color: green"><%= notice %></p>

<% if current_user.admin? %>
                       
    <% else %>
    <%= link_to new_employee_path, class: "btn btn-primary mt-3" do %>
        <i class="fa fa-plus"></i> Cadastrar Novo Morador
    <% end %>                 
<% end %>

<% if @employees.present? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-lg-9"> 
        <div class="right_col mt-3" role="main">
          <div class="row">
            <% @employees.each do |employee| %>
                <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="card mb-4">
                </br>
                    <div class="text-center">
                        <p>
                            <% if employee.profile_picture.attached? %>
                            <%= image_tag employee.profile_picture, size: '288x288' %>
                            <% else %>
                            <%= image_tag "user.png", size: '288x288' %>
                            <% end %>
                        </p>
                    </div>
                <div class="card-body">
                  <% employee.keylockers.each do |keylocker| %>
                    <p>
                    <strong>Codigo Postal:</strong> <%= keylocker.zip_code %>
                    </p>

                    <p>
                    <strong>Bairro:</strong> <%= keylocker.neighborhood %>
                    </p>

                    <p>
                    <strong>Rua:</strong> <%= keylocker.street %>
                    </p>

                    <p>
                    <strong>Cidade:</strong> <%= keylocker.city %>
                    </p>

                    <p>
                    <strong>Nome do edifício:</strong> <%= keylocker.nameBuilding %>
                    </p>
                  <% end %>

                  <p>
                    <strong>Nome:</strong>
                    <%= employee.name %> <%= employee.lastname %>
                  </p>

                  <p>
                    <strong>Sobrenome:</strong>
                    <%= employee.lastname %>
                  </p>

                  <p>
                    <strong>Numero do apartamento:</strong>
                    <%= employee.numberHouse %>
                  </p>

                  <p>
                    <strong>Telefone:</strong>
                    <%= employee.phone %>
                  </p>

                  <p>
                    <strong>Email:</strong>
                    <%= employee.email %>
                  </p>

                  <% if current_user.admin? %>
                    <p>
                        <% if employee.keylockers.any? %>
                         
                        <% else %>
                            Nenhum dispenser associado a esse colaborador.
                        <% end %>
                    </p>
                    <% else %>              
                  <% end %>
                 
                  <div class="text-center mt-3">
                    <%= link_to employee, class: "btn btn-warning d-inline-block mr-2" do %>
                      <i class="fa fa-search"></i> Exibir
                    <% end %>
                
                    <%= link_to edit_employee_path(employee), class: "btn btn-success d-inline-block mr-2" do %>
                        <i class="fa fa-edit"></i> Editar
                    <% end %>
                
                    <%= button_to employee, method: :delete, class: 'btn btn-danger d-inline-block mt-3', title: 'Excluir', id: "delete-btn-#{employee.id}" do %>
                        <i class="fa fa-trash"></i> Excluir
                    <% end %>   
                  </div>
                  </br>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div style="text-align: center;">
    <p>Não existe nenhum colaborador</p>
  </div>
<% end %>
            
<div class="text-center mt-3 d-flex justify-content-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <%= will_paginate @employees, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </ul>
  </nav>
</div>

<script>
$(document).ready(function() {
  $('[id^=delete-btn]').on('click', function(e) {
    e.preventDefault();

    var employeeId = $(this).attr('id').split('-')[2];

    if (confirm('Tem certeza?')) {
      $.ajax({
        url: '/employees/' + employeeId,
        method: 'DELETE',
        success: function() {
          // Atualiza a página após a exclusão bem-sucedida.
          location.reload(true);
        },
        error: function(error) {
          console.error('Erro ao excluir:', error);
          location.reload(true);
        }
      });
    }
  });
});
</script>

app/views/employees/new.html.erb
<%= render "form", employee: @employee %>

app/views/employees/show.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-users"></i> Morador</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<p style="color: green"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-lg-9"> 
      <div class="right_col mt-3" role="main">
        <div class="row">

          <div class="col-md-3">
            <% if @employee&.profile_picture&.attached? %>
              <%= image_tag @employee.profile_picture, class: "img-fluid rounded", style: "max-width: 100%;" %>
            <% else %>
              <%= image_tag "user.png", class: "img-fluid rounded", style: "max-width: 100%;" %>
            <% end %>
          </div>

          <div class="col-md-9">
            <p>
              <strong>Nome:</strong>
              <%= @employee.name %> <%= @employee.lastname %>
            </p>

            <p>
              <strong>Numero do apartamento:</strong>
              <%= @employee.numberHouse %>
            </p>

            <p>
              <strong>Telefone:</strong>
              <%= @employee.phone %>
            </p>

            <p>
              <strong>Email:</strong>
              <%= @employee.email %>
            </p>
              
            <div class="btn-group d-flex align-items-center">
              <%= link_to(edit_employee_path(@employee), class: "btn btn-primary mr-2") do %>
                <i class="fas fa-edit"></i> Editar
              <% end %>
              
              <%= link_to(employees_path, class: "btn btn-secondary mr-2") do %>
                <i class="fas fa-arrow-left"></i> Voltar
              <% end %>


              <%= button_to send_sms_employee_path(@employee), method: :post, class: "btn btn-info mr-2" do %>
                <i class="fas fa-phone"></i> Enviar SMS
              <% end %>

              <%= button_to send_email_employee_path(@employee), method: :post, class: "btn btn-warning mr-2" do %>
                <i class="fas fa-envelope"></i> Enviar E-mail
              <% end %>

              <%= button_to enviar_mensagem_whatsapp_path(@employee), method: :post, class: "btn btn-success mr-2" do %>
                <i class="fab fa-whatsapp"></i> Enviar Whatsapp
              <% end %>

              <%= button_to(@employee, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mr-2") do %>
                <i class="fas fa-trash-alt"></i> Excluir
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<h2>Histórico de Encomendas</h2>
<ul>
<% @employee.employee_actions.order(created_at: :desc).limit(10).reverse.each do |action| %>
  <li><%= action.action_description %></li>
  <% end %>
</ul>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById('reset-pin-btn').addEventListener('click', function() {
      // Chamar a ação AJAX para resetar PIN, enviar SMS e atualizar no banco de dados
      resetPinAndSendSMS('<%= @employee.phone %>');
    });

    function resetPinAndSendSMS(phone) {
      // Adicione lógica AJAX aqui
      $.ajax({
        type: 'PUT',
        url: '<%= reset_pin_employee_path(@employee) %>',
        data: { phone: phone },
        success: function(response) {
          alert(response.message); // Exiba uma mensagem de sucesso
        },
        error: function() {
          alert('Erro ao resetar o PIN e enviar por SMS.');
        }
      });
    }
  });
</script>