config/routes.rb
Rails.application.routes.draw do
  get 'settings/index'
  get 'historico/index'
  resources :valordoses
  get 'static_pages/inadimplente'
  root 'welcome#index'
  get 'admin', to: 'admin#index'
  get 'dadosuser', to: 'admin#dadosuser'
  get '/manager_users', to: 'manager_users#index', as: 'manager_users_index'
  get 'inadimplente', to: 'static_pages#inadimplente'
  resources :employees
  devise_for :users
  resources :keylockers 
  get 'historico', to: 'historico#index'
  get '/atualizar_soma_dinamica', to: 'keylockers#atualizar_soma_dinamica'

  get '/dispensers', to: 'keylockers#index', as: 'dispensers'
  get '/user_dispenser', to: 'manager_users#index', as: 'user_dispenser'
  get '/dispensers/new', to: 'keylockers#new', as: 'new_dispenser'

  get '/dispensers/:id', to: 'keylockers#show', as: 'dispenser', constraints: { id: /\d+/ }
  get '/dispensers/:id/edit', to: 'keylockers#edit', as: 'edit_dispenser', constraints: { id: /\d+/ }
  post 'user_mailer/send_email', to: 'user_mailer#send_email'
  post '/enviar_mensagem_whatsapp/:id', to: 'employees#enviar_mensagem_whatsapp', as: 'enviar_mensagem_whatsapp'


  resources :settings, only: [:index, :create]

  resources :employees do
    member do
      patch 'toggle_and_save_status'
      put 'reset_pin'
      post 'employees/send_email', to: 'employees#send_email'
      post 'send_email'
      post 'send_sms'
      post 'import', to: 'employees#import'
    end
    collection do
      post 'import', to: 'employees#import'
    end
  end

  resources :keylockers do
    member do
      post 'reset_counter'
      patch 'toggle_and_save_status'
    end
  end

  patch 'manager_users/:id/toggle_finance', to: 'manager_users#toggle_finance', as: :toggle_finance
  patch 'manager_users/:id/toggle_role', to: 'manager_users#toggle_role', as: :toggle_role

  resources :manager_users do
    member do
      delete :destroy
    end
  end

  get '/history_entries', to: 'history_entries#index'

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]

  resources :history_entries, only: [:index, :show, :new, :create, :destroy]


  # config/routes.rb
  resources :user_lockers do
    member do
      post 'assign_keylocker'
      delete 'remove_keylocker/:keylocker_id', to: 'user_lockers#remove_keylocker', as: 'remove_keylocker'
    end
  end

  

  #resources :keylockers, defaults: { format: 'json' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :employees
      post 'employees/check_access', to: 'employees#check_access'
      get '/employees', to: 'employees#index'
      post '/register_card', to: 'employees#register_card'
      post '/create_user', to: 'employees#create_user'
      get '/employees/:employee_id/belongs_to_keylocker/:keylocker_id', to: 'employees#belongs_to_keylocker'
      post '/libera_dose', to: 'employees#libera_dose', via: :post
      post 'check_user', to: 'employees#check_user'
      post 'count_and_track_spaces', to: 'employees#count_and_track_spaces'
      post 'return_key', to: 'employees#return_key'
      post 'key_locker_history', to: 'employees#key_locker_history'
      get '/outro_metodo', to: 'employees#outro_metodo'
      resources :keylockers do
        member do
          post 'increment_counter'
        end
      end
      #post '/auth/sign_in', to: 'authentication#sign_in'
      devise_for :users, skip: [:registrations], controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :keylockers
    has_one_attached :profile_picture
    has_many :employee_actions

    validate :at_least_one_keylocker

  
    private

    def at_least_one_keylocker
      errors.add(:base, 'Deve haver pelo menos um dispenser atribuído') if keylockers.none?
    end
  
    
  end
  

app/models/employee_action.rb
class EmployeeAction < ApplicationRecord
    belongs_to :employee
end

app/models/history_entry.rb
class HistoryEntry < ApplicationRecord
  validates :saveCards, uniqueness: true  
end

app/models/keylocker.rb
class Keylocker < ApplicationRecord
    #validates_uniqueness_of :owner, scope: [:nameDevice, :status]
    has_many :user_lockers
    has_many :users, through: :user_lockers
    has_many :employees_keylockers
    has_and_belongs_to_many :employees

    after_update :atualizar_valordose, if: :contDose_changed?

    def toggle_and_save_status!
        # Implemente a lógica para alternar e salvar o status no banco de dados
        self.status = (status == 'bloqueado' ? 'desbloqueado' : 'bloqueado')
        save!
    end

    private
end

app/models/keylog.rb
class Keylog < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  validates :message, presence: true

  def formatted_employee_info
    formatted_info = ""
    if employee_info.is_a?(Hash)
      employee_info.each do |key, value|
        formatted_info << "#{key.capitalize}: #{value}\n"
      end
    else
      formatted_info = employee_info
    end
    formatted_info << "\nCreated At: #{created_at}"
    formatted_info
  end
end

app/models/setting.rb
class Setting < ApplicationRecord

end
  

app/models/user.rb
class User < ApplicationRecord
  before_create :set_default_role
  before_create :set_default_finance
  enum role: { admin: 'admin', user: 'user'}

  has_many :user_lockers
  has_many :keylockers, through: :user_lockers
  has_one :employee #funciona
  has_one :keylocker  # Adicione esta linha
  has_one :address
  has_many :valordoses


  #accepts_nested_attributes_for :employees

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_save :ensure_authentication_token

  # Método para atribuir um locker a um usuário
  def assign_keylocker(keylocker)
    self.keylockers << keylocker unless self.keylockers.include?(keylocker)
  end

  # Método para remover um locker de um usuário
  def remove_keylocker(keylocker)
    self.keylockers.delete(keylocker)
  end


  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  private

  def set_default_role
    self.role ||= 'user'
  end

  def set_default_finance
    self.finance ||= 'adimplente'
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.find_by(authentication_token: token)
    end
  end  
end

app/models/user_locker.rb
class UserLocker < ApplicationRecord
  belongs_to :user
  belongs_to :keylocker
end

app/models/valordose.rb
class Valordose < ApplicationRecord
end

app/models/workday.rb
class Workday < ApplicationRecord
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/historico_helper.rb
module HistoricoHelper
end

app/helpers/historicos_helper.rb
module HistoricosHelper
end

app/helpers/keylockers_helper.rb
module KeylockersHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/valordoses_helper.rb
module ValordosesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dadosuser.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Dados do Usuário</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 col-lg-9"> 
            <div class="right_col mt-3" role="main">
                <div class="row">

                    <p>
                        <strong>Perfil de usuário:</strong>
                        <% if current_user.role == 'user' %>
                            <button class="btn btn-primary">
                                <i class="fas fa-user"></i> Usuário
                            </button>
                            <% elsif current_user.role == 'admin' %>
                            <button class="btn btn-success">
                                <i class="fas fa-user-tie"></i> Administrador
                            </button>
                        <% end %>
                    </p>
            
                    <p>
                        <strong>Nome:</strong>
                        <%= current_user.name %> <%= current_user.lastname %>
                    </p>
            
                    <p>
                        <strong>Nome da Empresa:</strong>
                        <%= current_user.nameCompany %> 
                    </p>
            
                    <p>
                        <strong>CNPJ:</strong>
                        <%= current_user.cnpj %>
                    </p>
            
                    <p>
                        <strong>Email:</strong>
                        <%= current_user.email %>
                    </p>
            
                    <p>
                        <strong>Status Financeiro:</strong>
                        <% if current_user.finance == 'adimplente' %>
                            <button class="btn btn-success">
                                <i class="fas fa-check"></i> Adimplente
                            </button>
                            <% elsif current_user.finance == 'inadimplente' %>
                            <button class="btn btn-warning">
                                <i class="fas fa-exclamation-triangle"></i> Inadimplente
                            </button>
                        <% end %>
                    </p>
            
                    <p>
                        <strong>Celular:</strong>
                        <%= current_user.phone %>
                    </p>
            
                    <p>
                        <strong>Código Postal:</strong>
                        <%= current_user.zip_code %>
                    </p>
            
                    <p>
                        <strong>Rua:</strong>
                        <%= current_user.street %>
                    </p>
            
                    <p>
                        <strong>Cidade:</strong>
                        <%= current_user.city %>
                    </p>
            
                    <p>
                        <strong>Estado:</strong>
                        <%= current_user.state %>
                    </p>
            
                    <p>
                        <strong>Bairro:</strong>
                        <%= current_user.neighborhood %>
                    </p>
            
                    <p>
                        <strong>Complemento:</strong>
                        <%= current_user.complement %>
                    </p>
            
                    <p>
                        <strong>Criado em:</strong>
                        <%= current_user.created_at.strftime('%d/%m/%Y - %H:%M:%S') %>
                    </p>
            
                    <p>
                        <strong>Última alteração:</strong>
                        <%= current_user.updated_at.strftime('%d/%m/%Y - %H:%M:%S') %>
                    </p>
                
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/index.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Meus Funcionários Admin</h1>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <% if current_user.admin? %>
                        <p>Você é um administrador.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <%= link_to "New keylocker", new_keylocker_path %>
                        <%= link_to "Atribuir locker", user_lockers_path %>
                        <%= link_to "Ver funconarios", admin_path %>
                        <% else %>
                        <p>Você é um usuário regular.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                            <%= link_to "New employee", new_employee_path %>
                        <% end %>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<p style="color: green"><%= notice %></p>

<% if @employees.present? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-lg-9"> 
        <div class="right_col mt-3" role="main">
          <div class="row">
            <% @employees.each do |employee| %>
              <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="card mb-4">
                </br>
                    <div class="text-center">
                        <p>
                            <% if employee.profile_picture.attached? %>
                            <%= image_tag employee.profile_picture, size: '288x288' %>
                            <% else %>
                            <p>Nenhuma imagem disponível</p>
                            <% end %>
                        </p>
                    </div>
                <div class="card-body">
                  <p>
                    <strong>Nome:</strong>
                    <%= employee.name %> <%= employee.lastname %>
                  </p>

                  <p>
                    <strong>Empresa:</strong>
                    <%= employee.companyID %>
                  </p>

                  <p>
                    <strong>Telefone:</strong>
                    <%= employee.phone %>
                  </p>

                  <p>
                    <strong>Cargo:</strong>
                    <%= employee.function %>
                  </p>

                  <p>
                    <strong>Meus Lockers:</strong>
                    <% if employee.keylockers.any? %>
                        <ul>
                        <% employee.keylockers.each do |keylocker| %>
                            <li>
                            <%= keylocker.nameDevice %> - <%= keylocker.status %>
                            </li>
                        <% end %>
                        </ul>
                    <% else %>
                        Nenhum locker associado a esse funcionário.
                    <% end %>
                  </p>

                  <div class="text-center mt-3">
                    <%= link_to employee, class: "btn btn-warning d-inline-block mr-2" do %>
                      <i class="fa fa-search"></i> Exibir
                    <% end %>
                
                    <%= link_to edit_employee_path(employee), class: "btn btn-success d-inline-block mr-2" do %>
                        <i class="fa fa-edit"></i> Editar
                    <% end %>
                
                    <%= button_to employee, method: :delete, class: 'btn btn-danger d-inline-block mt-3', title: 'Excluir', id: "delete-btn-#{employee.id}" do %>
                        <i class="fa fa-trash"></i> Excluir
                    <% end %>                  
                  </div>
                  </br>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div style="text-align: center;">
    <p>Não existe nenhum colaborador</p>
  </div>
<% end %>



<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-user-tie"></i> Controle Funcionários x Lockers</h1>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <% if current_user.admin? %>
                        <p>Você é um administrador.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                        <%= link_to "New keylocker", new_keylocker_path %>
                        <%= link_to "Atribuir locker", user_lockers_path %>
                        <%= link_to "Ver funconarios", admin_path %>
                        <% else %>
                        <p>Você é um usuário regular.</p>
                        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                            <%= link_to "New employee", new_employee_path %>
                        <% end %>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

Tabela de Employees x Keylockers

<h1>Employees and their Associated Lockers</h1>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
            <th>Employee ID</th>
            <th>Employee Name</th>
            <th>Locker ID</th>
            <th>Locker Name</th>
            </tr>
        </thead>
        <tbody>
            <% @employees.each do |employee| %>
            <% employee.keylockers.each do |keylocker| %>
                <tr>
                <td><%= employee.id %></td>
                <td><%= employee.name %></td>
                <td><%= keylocker.id %></td>
                <td><%= keylocker.nameDevice %></td>
                </tr>
            <% end %>
            <% end %>
        </tbody>
    </table>
</div>