config/routes.rb
Rails.application.routes.draw do
  get 'settings/index'
  get 'historico/index'
  resources :valordoses
  get 'static_pages/inadimplente'
  root 'welcome#index'
  get 'admin', to: 'admin#index'
  get 'dadosuser', to: 'admin#dadosuser'
  get '/manager_users', to: 'manager_users#index', as: 'manager_users_index'
  get 'inadimplente', to: 'static_pages#inadimplente'
  resources :employees
  devise_for :users
  resources :keylockers 
  get 'historico', to: 'historico#index'
  get '/atualizar_soma_dinamica', to: 'keylockers#atualizar_soma_dinamica'

  get '/dispensers', to: 'keylockers#index', as: 'dispensers'
  get '/user_dispenser', to: 'manager_users#index', as: 'user_dispenser'
  get '/dispensers/new', to: 'keylockers#new', as: 'new_dispenser'

  get '/dispensers/:id', to: 'keylockers#show', as: 'dispenser', constraints: { id: /\d+/ }
  get '/dispensers/:id/edit', to: 'keylockers#edit', as: 'edit_dispenser', constraints: { id: /\d+/ }
  post 'user_mailer/send_email', to: 'user_mailer#send_email'
  post '/enviar_mensagem_whatsapp/:id', to: 'employees#enviar_mensagem_whatsapp', as: 'enviar_mensagem_whatsapp'


  resources :settings, only: [:index, :create]

  resources :employees do
    member do
      patch 'toggle_and_save_status'
      put 'reset_pin'
      post 'employees/send_email', to: 'employees#send_email'
      post 'send_email'
      post 'send_sms'
      post 'import', to: 'employees#import'
    end
    collection do
      post 'import', to: 'employees#import'
    end
  end

  resources :keylockers do
    member do
      post 'reset_counter'
      patch 'toggle_and_save_status'
    end
  end

  patch 'manager_users/:id/toggle_finance', to: 'manager_users#toggle_finance', as: :toggle_finance
  patch 'manager_users/:id/toggle_role', to: 'manager_users#toggle_role', as: :toggle_role

  resources :manager_users do
    member do
      delete :destroy
    end
  end

  get '/history_entries', to: 'history_entries#index'

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]

  resources :history_entries, only: [:index, :show, :new, :create, :destroy]


  # config/routes.rb
  resources :user_lockers do
    member do
      post 'assign_keylocker'
      delete 'remove_keylocker/:keylocker_id', to: 'user_lockers#remove_keylocker', as: 'remove_keylocker'
    end
  end

  

  #resources :keylockers, defaults: { format: 'json' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :employees
      post 'employees/check_access', to: 'employees#check_access'
      get '/employees', to: 'employees#index'
      post '/register_card', to: 'employees#register_card'
      post '/create_user', to: 'employees#create_user'
      get '/employees/:employee_id/belongs_to_keylocker/:keylocker_id', to: 'employees#belongs_to_keylocker'
      post '/libera_dose', to: 'employees#libera_dose', via: :post
      post 'check_user', to: 'employees#check_user'
      post 'count_and_track_spaces', to: 'employees#count_and_track_spaces'
      post 'return_key', to: 'employees#return_key'
      post 'key_locker_history', to: 'employees#key_locker_history'
      get '/outro_metodo', to: 'employees#outro_metodo'
      resources :keylockers do
        member do
          post 'increment_counter'
        end
      end
      #post '/auth/sign_in', to: 'authentication#sign_in'
      devise_for :users, skip: [:registrations], controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_create :set_default_role
  before_create :set_default_finance
  enum role: { admin: 'admin', user: 'user'}

  has_many :user_lockers
  has_many :keylockers, through: :user_lockers
  has_one :employee #funciona
  has_one :keylocker  # Adicione esta linha
  has_one :address
  has_many :valordoses


  #accepts_nested_attributes_for :employees

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_save :ensure_authentication_token

  # Método para atribuir um locker a um usuário
  def assign_keylocker(keylocker)
    self.keylockers << keylocker unless self.keylockers.include?(keylocker)
  end

  # Método para remover um locker de um usuário
  def remove_keylocker(keylocker)
    self.keylockers.delete(keylocker)
  end


  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  private

  def set_default_role
    self.role ||= 'user'
  end

  def set_default_finance
    self.finance ||= 'adimplente'
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.find_by(authentication_token: token)
    end
  end  
end

app/models/user_locker.rb
class UserLocker < ApplicationRecord
  belongs_to :user
  belongs_to :keylocker
end

app/controllers/user_lockers_controller.rb
# app/controllers/user_lockers_controller.rb
class UserLockersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
    @keylockers = Keylocker.all.paginate(page: params[:page], per_page: 10)
  end

  def assign_keylocker
    @user = User.find(params[:user_id])
    keylocker = Keylocker.find(params[:keylocker_id])
    if @user && keylocker
      @user.keylockers << keylocker
      redirect_to user_lockers_path, notice: 'Locker atribuído ao usuário com sucesso.'
    else
      redirect_to user_lockers_path, alert: 'Falha ao atribuir locker ao usuário.'
    end
  end

  def remove_keylocker
    Rails.logger.debug "Entrou na função remove_keylocker!"
    puts"user_id: #{params[:user_id]}, keylocker_id: #{params[:keylocker_id]}"


    @user = User.find(params[:user_id])
    keylocker = Keylocker.find(params[:keylocker_id])

    Rails.logger.debug "user_id: #{params[:user_id]}, keylocker_id: #{params[:keylocker_id]}"
    puts"user_id: #{params[:user_id]}, keylocker_id: #{params[:keylocker_id]}"

    if @user && keylocker
      @user.keylockers.delete(keylocker)
      redirect_to user_lockers_path, notice: 'Locker removido do usuário com sucesso.'
    else
      redirect_to user_lockers_path, alert: 'Falha ao remover locker do usuário.'
    end
  end

  private

  private

  def authenticate_admin!
    unless current_user.admin?
      flash[:alert] = "Acesso não autorizado."
      redirect_to root_path
    end
  end
end

app/helpers/user_lockers_helper.rb
module UserLockersHelper
end

app/views/user_lockers/assign_keylocker.html.erb
<h1>UserLockers#assign_locker</h1>
<p>Find me in app/views/user_lockers/assign_locker.html.erb</p>

<!-- Adapte conforme necessário -->
<h1>Atribuir Keylocker</h1>

<%= render 'form', user_locker: @user_locker %>

<%= link_to 'Voltar', user_lockers_path %>

app/views/user_lockers/index.html.erb
<p style="color: green"><%= notice %></p>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-building"></i> Atribuir Prédios</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <th>Nome</th>
        <th>Atribuir Prédio</th>
        <th>Remover Prédio</th>
        <th>Prédios Atribuídos</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
          <td>
            <%= form_tag assign_keylocker_user_locker_path(user), method: :post do %>
              <%= hidden_field_tag :user_id, user.id %>
              <% available_keylockers = Keylocker.where.not(id: user.keylocker_ids) %>
              <%= select_tag :keylocker_id, options_for_select(available_keylockers.map { |k| [k.nameBuilding, k.id] }) %>
              <%= submit_tag 'Atribuir Prédio', class: 'btn btn-primary' %>
            <% end %>
          </td>
          <td>
            <% user.keylockers.each do |keylocker| %>
              <%= form_tag remove_keylocker_user_locker_path(user, keylocker), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <%= hidden_field_tag 'user_id', user.id %>
                <%= hidden_field_tag :keylocker_id, keylocker.id %>
                <%= submit_tag "Remover #{keylocker.nameBuilding}", class: 'btn btn-danger mt-3' %>
              <% end %>
            <% end %>
          </td>
          <td>
            <ul>
              <% user.keylockers.each do |keylocker| %>
                <li><%= keylocker.nameBuilding %></li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="text-center mt-3 d-flex justify-content-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <%= will_paginate @keylockers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </ul>
  </nav>
</div>

app/views/user_lockers/remove_keylocker.html.erb
<!-- Adapte conforme necessário -->
<h1>Remover Keylocker</h1>

<%= render 'form', user_locker: @user_locker %>

<%= link_to 'Voltar', user_lockers_path %>