config/routes.rb
Rails.application.routes.draw do
  get 'settings/index'
  get 'historico/index'
  resources :valordoses
  get 'static_pages/inadimplente'
  root 'welcome#index'
  get 'admin', to: 'admin#index'
  get 'dadosuser', to: 'admin#dadosuser'
  get '/manager_users', to: 'manager_users#index', as: 'manager_users_index'
  get 'inadimplente', to: 'static_pages#inadimplente'
  resources :employees
  devise_for :users
  resources :keylockers 
  get 'historico', to: 'historico#index'
  get '/atualizar_soma_dinamica', to: 'keylockers#atualizar_soma_dinamica'

  get '/dispensers', to: 'keylockers#index', as: 'dispensers'
  get '/user_dispenser', to: 'manager_users#index', as: 'user_dispenser'
  get '/dispensers/new', to: 'keylockers#new', as: 'new_dispenser'

  get '/dispensers/:id', to: 'keylockers#show', as: 'dispenser', constraints: { id: /\d+/ }
  get '/dispensers/:id/edit', to: 'keylockers#edit', as: 'edit_dispenser', constraints: { id: /\d+/ }
  post 'user_mailer/send_email', to: 'user_mailer#send_email'
  post '/enviar_mensagem_whatsapp/:id', to: 'employees#enviar_mensagem_whatsapp', as: 'enviar_mensagem_whatsapp'


  resources :settings, only: [:index, :create]

  resources :employees do
    member do
      patch 'toggle_and_save_status'
      put 'reset_pin'
      post 'employees/send_email', to: 'employees#send_email'
      post 'send_email'
      post 'send_sms'
      post 'import', to: 'employees#import'
    end
    collection do
      post 'import', to: 'employees#import'
    end
  end

  resources :keylockers do
    member do
      post 'reset_counter'
      patch 'toggle_and_save_status'
    end
  end

  patch 'manager_users/:id/toggle_finance', to: 'manager_users#toggle_finance', as: :toggle_finance
  patch 'manager_users/:id/toggle_role', to: 'manager_users#toggle_role', as: :toggle_role

  resources :manager_users do
    member do
      delete :destroy
    end
  end

  get '/history_entries', to: 'history_entries#index'

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]

  resources :history_entries, only: [:index, :show, :new, :create, :destroy]


  # config/routes.rb
  resources :user_lockers do
    member do
      post 'assign_keylocker'
      delete 'remove_keylocker/:keylocker_id', to: 'user_lockers#remove_keylocker', as: 'remove_keylocker'
    end
  end

  

  #resources :keylockers, defaults: { format: 'json' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :employees
      post 'employees/check_access', to: 'employees#check_access'
      get '/employees', to: 'employees#index'
      post '/register_card', to: 'employees#register_card'
      post '/create_user', to: 'employees#create_user'
      get '/employees/:employee_id/belongs_to_keylocker/:keylocker_id', to: 'employees#belongs_to_keylocker'
      post '/libera_dose', to: 'employees#libera_dose', via: :post
      post 'check_user', to: 'employees#check_user'
      post 'count_and_track_spaces', to: 'employees#count_and_track_spaces'
      post 'return_key', to: 'employees#return_key'
      post 'key_locker_history', to: 'employees#key_locker_history'
      get '/outro_metodo', to: 'employees#outro_metodo'
      resources :keylockers do
        member do
          post 'increment_counter'
        end
      end
      #post '/auth/sign_in', to: 'authentication#sign_in'
      devise_for :users, skip: [:registrations], controllers: {
        sessions: 'api/v1/auth/sessions'
      }
    end
  end
end

app/models/keylocker.rb
class Keylocker < ApplicationRecord
    #validates_uniqueness_of :owner, scope: [:nameDevice, :status]
    has_many :user_lockers
    has_many :users, through: :user_lockers
    has_many :employees_keylockers
    has_and_belongs_to_many :employees

    after_update :atualizar_valordose, if: :contDose_changed?

    def toggle_and_save_status!
        # Implemente a lógica para alternar e salvar o status no banco de dados
        self.status = (status == 'bloqueado' ? 'desbloqueado' : 'bloqueado')
        save!
    end

    private
end

app/controllers/api/v1/keylockers_controller.rb
# app/controllers/api/v1/keylockers_controller.rb
module Api
    module V1
      class KeylockersController < ApplicationController
        before_action :set_keylocker, only: [:show, :update, :destroy, :increment_counter]
        skip_before_action :verify_authenticity_token, only: [:new, :create, :update, :increment_counter]
        skip_before_action :authenticate_user!, only: [:new, :create, :update, :increment_counter]
        protect_from_forgery with: :null_session

        # GET /keylockers or /keylockers.json
        def index
          @keylockers = Keylocker.all
          render json: @keylockers
        end


        # GET /keylockers/new
        def new
          @keylocker = Keylocker.new
        end

        # GET /keylockers/1 or /keylockers/1.json
        def show
          render json: @keylocker
        end

      
        # POST /keylockers or /keylockers.json
        def create
          @keylocker = Keylocker.new(keylocker_params)
          
          @keylocker.setdose ||= 200
          @keylocker.valuedrink ||= 2.50
          @keylocker.total ||= 0

        
          respond_to do |format|
            if @keylocker.save
              format.json { render json: { message: "Dispenser foi criado com sucesso.", keylocker: @keylocker }, status: :created, location: @keylocker }
            else
              format.json { render json: @keylocker.errors, status: :unprocessable_entity }
            end
          end
        end

        # PATCH/PUT /api/v1/keylockers/1
        def update
          if @keylocker.update(keylocker_params)
            render json: @keylocker
          else
            render json: @keylocker.errors, status: :unprocessable_entity
          end
        end
        
        # DELETE /api/v1/keylockers/1
        def destroy
          @keylocker.destroy
          head :no_content
        end

        def increment_counter
          if @keylocker
            if @keylocker.increment!(:contDose, 1)
              current_valuedrink = @keylocker.valuedrink.to_f
              current_contDose = @keylocker.contDose
              new_valuedrink = current_valuedrink * current_contDose
              @keylocker.update(total: new_valuedrink)
              render json: @keylocker
            else
              render json: { error: "Erro ao incrementar o contador." }, status: :unprocessable_entity
            end
          else
            render json: { error: "Keylocker não encontrado." }, status: :not_found
          end
        end

        private
          # Use callbacks to share common setup or constraints between actions.
          def set_keylocker
            @keylocker = Keylocker.find(params[:id])
          end

          # Only allow a list of trusted parameters through.
          def keylocker_params
            params.require(:keylocker).permit(:owner, :nameDevice, :ipAddress, :status, :contDose, :fullmax, :setdose, :valuedrink, :total)
          end
      end
    end
  end
  

app/controllers/keylockers_controller.rb
class KeylockersController < ApplicationController
  before_action :set_keylocker, only: %i[ show edit update destroy ]
  #before_action :authenticate_admin_user! # Certifique-se de ter um método de autenticação de admin
  skip_before_action :verify_authenticity_token, only: [:toggle_and_save_status]
  skip_before_action :authenticate_user!, only: [:toggle_and_save_status]

  # GET /keylockers or /keylockers.json
  def index
    if current_user.admin?
      @keylockers = Keylocker.all.paginate(page: params[:page], per_page: 9)
    else
      @keylockers = current_user.keylockers.paginate(page: params[:page], per_page: 9)
    end
  end

  # GET /keylockers/1 or /keylockers/1.json
  def show
  end

  # GET /keylockers/new
  def new
    @keylocker = Keylocker.new
  end

  # GET /keylockers/1/edit
  def edit
  end

  # POST /keylockers or /keylockers.json
  def create
    @keylocker = Keylocker.new(keylocker_params)
    respond_to do |format|
      if @keylocker.save
        format.html { redirect_to keylocker_url(@keylocker), notice: "Keylocker was successfully created." }
        format.json { render :show, status: :created, location: @keylocker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keylocker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keylockers/1 or /keylockers/1.json
  def update
    respond_to do |format|
      if @keylocker.update(keylocker_params)
        format.html { redirect_to keylocker_url(@keylocker), notice: "Keylocker was successfully updated." }
        format.json { render :show, status: :ok, location: @keylocker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keylocker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keylockers/1 or /keylockers/1.json
  def destroy
    @keylocker.destroy

    respond_to do |format|
      format.html { redirect_to keylockers_url, notice: "Keylocker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reset_counter
    if Keylocker.update_all(contDose: 0)
      redirect_to keylockers_path, notice: "Contador resetado com sucesso."
    else
      redirect_to keylockers_path, alert: "Erro ao resetar o contador."
    end
  end

  def assign_keylocker
    user = User.find(params[:user_id])
    keylocker = Keylocker.find(params[:keylocker_id])
    #user.assign_keylocker(keylocker)
    user.keylockers << keylocker
    redirect_to users_path, notice: 'Locker atribuído com sucesso!'
  end

  def remove_keylocker
    #user_locker = UserLocker.find_by(user_id: params[:user_id], keylocker_id: @keylocker.id)
    #user_locker.destroy if user_locker.present?
    user = User.find(params[:user_id])
    keylocker = Keylocker.find(params[:keylocker_id])
    user.remove_keylocker(keylocker)
    redirect_to users_path, notice: 'Locker removido com sucesso!'
  end

  def toggle_and_save_status
    @keylocker = Keylocker.find(params[:id])
    @keylocker.toggle_and_save_status! # Supondo que você tenha um método correspondente no modelo

    respond_to do |format|
      format.json { render json: { status: @keylocker.status } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keylocker
      @keylocker = Keylocker.find(params[:id])
    end

    def authenticate_admin_user!
      # Adicione lógica para verificar se o usuário é um administrador.
      # Você pode usar Devise's current_user ou outra lógica personalizada.
    end

    # Only allow a list of trusted parameters through.
    def keylocker_params
      params.require(:keylocker).permit(:street, :city, :state, :zip_code, :neighborhood, :nameBuilding, :complement)
    end
end

app/helpers/keylockers_helper.rb
module KeylockersHelper
end

app/views/keylockers/_form.html.erb
<%= form_with(model: keylocker) do |form| %>
  <% if keylocker.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(keylocker.errors.count, "error") %> prohibited this keylocker from being saved:</h2>

      <ul>
        <% keylocker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-8 mb-4">
    <div class="card mb-4">
      <div class="card-header py-3">
        <h5 class="mb-0">Cadastrar um novo prédio</h5>
      </div>
      <div class="card-body">

        <form method="get" action=".">
          <div class="form-outline mb-4">
            <%= form.label :Nome_do_edificio, class: "form-label" %>
            <%= form.text_field :nameBuilding, class: 'form-control' %>
          </div>

        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              <%= form.label :Codigo_Postal, class: "form-label" %>
              <%= form.text_field :zip_code, id: 'cep', class: 'form-control', onblur:"pesquisacep(this.value);" %>
            </div>
          </div>

          <div class="col">
            <div class="form-outline">
              <%= form.label :Rua, class: "form-label" %>
              <%= form.text_field :street, id: 'rua', onblur:"pesquisacep(this.value);", class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              <%= form.label :Cidade, class: "form-label" %>
              <%= form.text_field :city, id: 'cidade', class: 'form-control' %>
            </div>
          </div>

          <div class="col">
            <div class="form-outline">
              <%= form.label :Estado, class: "form-label" %>
              <%= form.text_field :state, id: 'uf', class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="row mb-4">
          <div class="col">
            <div class="form-outline">
              <%= form.label :Bairro, class: "form-label" %>
              <%= form.text_field :neighborhood, id: 'bairro', class: 'form-control' %>
            </div>
          </div>

          <div class="col">
            <div class="form-outline">
              <%= form.label :Complemento, class: "form-label" %>
              <%= form.text_field :complement, class: 'form-control' %>
            </div>
          </div>                
        </div>
   
           
          <div class="d-flex">
            <div class="form-group mr-2">
              <%= form.submit 'Cadastrar Prédio', class: 'btn btn-primary' %>
            </div>

            <div class="form-group">
              <%= link_to "Voltar", dispensers_path, class: 'btn btn-success' %>
            </div> 
          </div>

        <% end %>
        </form>
      </div>
    </div>
  </div>



<script>
  function limpa_formulário_cep() {
          //Limpa valores do formulário de cep.
          document.getElementById('rua').value=("");
          document.getElementById('bairro').value=("");
          document.getElementById('cidade').value=("");
          document.getElementById('uf').value=("");
  }

  function meu_callback(conteudo) {
      if (!("erro" in conteudo)) {
          //Atualiza os campos com os valores.
          document.getElementById('rua').value=(conteudo.logradouro);
          document.getElementById('bairro').value=(conteudo.bairro);
          document.getElementById('cidade').value=(conteudo.localidade);
          document.getElementById('uf').value=(conteudo.uf);
      } //end if.
      else {
          //CEP não Encontrado.
          limpa_formulário_cep();
          alert("CEP não encontrado.");
      }
  }
      
  function pesquisacep(valor) {

      //Nova variável "cep" somente com dígitos.
      var cep = valor.replace(/\D/g, '');

      //Verifica se campo cep possui valor informado.
      if (cep != "") {

          //Expressão regular para validar o CEP.
          var validacep = /^[0-9]{8}$/;

          //Valida o formato do CEP.
          if(validacep.test(cep)) {

              //Preenche os campos com "..." enquanto consulta webservice.
              document.getElementById('rua').value="...";
              document.getElementById('bairro').value="...";
              document.getElementById('cidade').value="...";
              document.getElementById('uf').value="...";

              //Cria um elemento javascript.
              var script = document.createElement('script');

              //Sincroniza com o callback.
              script.src = 'https://viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';

              //Insere script no documento e carrega o conteúdo.
              document.body.appendChild(script);

          } //end if.
          else {
              //cep é inválido.
              limpa_formulário_cep();
              alert("Formato de CEP inválido.");
          }
      } //end if.
      else {
          //cep sem valor, limpa formulário.
          limpa_formulário_cep();
      }
  };
</script>

app/views/keylockers/_keylocker.html.erb
<div id="<%= dom_id keylocker %>">
  <p>
    <strong>Codigo Postal:</strong>
    <%= @keylocker.zip_code %>
  </p>

  
  <p>
    <strong>Nome do edifício:</strong>
    <%= @keylocker.nameBuilding %>
  </p> 

  <p>
    <strong>Bairro:</strong>
    <%= @keylocker.neighborhood %>
  </p> 

  <p>
    <strong>Rua:</strong>
    <%= @keylocker.street %>
  </p> 

  <p>
    <strong>Estado:</strong>
    <%= @keylocker.state %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= @keylocker.city %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= @keylocker.complement %> ml
  </p>
</div>

app/views/keylockers/edit.html.erb
<%= render "form", keylocker: @keylocker %>

app/views/keylockers/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-building"></i> Meus Prédios</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>


<% if current_user.admin? %>
  <%= link_to new_dispenser_path, class: "btn btn-primary mt-3" do %>
    <i class="fa fa-plus"></i> Cadastrar Novo Prédio
  <% end %>
  <% else %>
                
<% end %>

<% if @keylockers.present? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-lg-9">  
        <div class="right_col mt-3" role="main">
          <div class="row">
            <% @keylockers.each do |keylocker| %>
              <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="card mb-4">
                <%= image_tag 'predio.jpg', class: 'card-img-top', alt: 'Produto 1' %>
                 <div class="card-body">
                    <!-- Seu conteúdo de card -->
                    <p>
                      <strong>Nome do edifício:</strong>
                      <%= keylocker.nameBuilding %>
                    </p> 

                    <p>
                      <strong>Codigo Postal:</strong>
                      <%= keylocker.zip_code %>
                    </p>

                    <p>
                      <strong>Bairro:</strong>
                      <%= keylocker.neighborhood %>
                    </p> 
                      
                    <p>
                      <strong>Rua:</strong>
                      <%= keylocker.street %>
                    </p> 
                    
                    <p>
                      <strong>Estado:</strong>
                      <%= keylocker.state %>
                    </p>

                    <p>
                      <strong>Cidade:</strong>
                      <%= keylocker.city %>
                    </p>

                    <p>
                      <strong>Complemento:</strong>
                      <%= keylocker.complement %>
                    </p>
                 

                    <div class="text-center mt-3">
                    <%= link_to dispenser_path(id: keylocker.id), class: "btn btn-warning" do %>
                      <i class="fa fa-search"></i> Exibir
                      <% end %>  
                    </div>

                  </div>
                </div>
              </div>
            <% end %>
            <% else %>
              <div style="text-align: center;">
                <p>Não existe nenhum locker</p>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="text-center mt-3 d-flex justify-content-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <%= will_paginate @employees, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </ul>
  </nav>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
  $(document).ready(function() {
    // Adicione um manipulador de eventos para todos os elementos com a classe "toggle-status-btn"
    $('.toggle-status-btn').on('click', function() {
      var clickedButton = $(this);
      var keylockerId = clickedButton.data('keylocker-id');
      var statusText = $('.status-text[data-keylocker-id="' + keylockerId + '"]');

      $.ajax({
        url: '/keylockers/' + keylockerId + '/toggle_and_save_status',
        method: 'PATCH',
        success: function(data) {
          // Atualize visualmente o status e o ícone do botão apenas para o botão clicado
          statusText.text(data.status);

          var lockIcon = clickedButton.find('.lock-icon');
          
          // Remova apenas as classes relacionadas ao ícone
          lockIcon.removeClass('fa-lock fa-unlock');
          
          // Adicione a classe correta com base no novo status
          lockIcon.addClass(data.status == 'bloqueado' ? 'fa-lock' : 'fa-unlock');

          // Atualize a classe do botão apenas para o botão clicado
          clickedButton.removeClass('btn-danger btn-primary');
          clickedButton.addClass(data.status == 'bloqueado' ? 'btn-danger' : 'btn-primary');

          // Atualize o texto dentro do botão
          clickedButton.html('<i class="' + lockIcon.attr('class') + '"></i> ' + data.status);
        },
        error: function(error) {
          console.error('Erro ao alternar e salvar o status:', error);
        }
      });
    });
  });
</script>

app/views/keylockers/new.html.erb
<%= render "form", keylocker: @keylocker %>

app/views/keylockers/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li class="active">
                        <h1><i class="fas fa-building"></i> Meus Prédios</h1>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 col-lg-9"> 
            <div class="right_col mt-3" role="main">
                <div class="row">
                    <div class="col-md-3">
                        <%= image_tag 'predio.jpg', class: 'card-img-top', alt: 'Produto 1' %>
                    </div>
                    <div class="col-md-9">

                      <p>
                        <strong>Nome do edifício:</strong>
                        <%= @keylocker.nameBuilding %>
                      </p> 

                      <p>
                        <strong>Codigo Postal:</strong>
                        <%= @keylocker.zip_code %>
                      </p>

                      <p>
                        <strong>Bairro:</strong>
                        <%= @keylocker.neighborhood %>
                      </p> 
                      
                      <p>
                        <strong>Rua:</strong>
                        <%= @keylocker.street %>
                      </p> 
                    
                      <p>
                        <strong>Estado:</strong>
                        <%= @keylocker.state %>
                      </p>

                      <p>
                        <strong>Cidade:</strong>
                        <%= @keylocker.city %>
                      </p>

                      <p>
                        <strong>Complemento:</strong>
                        <%= @keylocker.complement %>
                      </p>
                    
                      <div class="btn-group">
                      <%= link_to edit_dispenser_path(@keylocker), class: "btn btn-primary mr-2" do %>
                        <i class="fas fa-edit"></i> Editar
                      <% end %>
                      
                      <%= link_to dispensers_path, class: "btn btn-secondary mr-2" do %>
                        <i class="fas fa-arrow-left"></i> Voltar
                      <% end %>
                      
                      <%= button_to @keylocker, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mr-2" do %>
                        <i class="fas fa-trash-alt"></i> Excluir
                      <% end %>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>